export default ROUTES = {
  TABNAVIGATOR: 'TABNAVIGATOR',
  CHARACTERS: 'CHARACTERS',
  EPISODES: 'EPISODES',
  LOCATIONS: 'LOCATIONS',
  SETTINGS: 'SETTINGS',
  CHARACTERDETAIL: 'CHARACTERDETAIL',
  SEARCHCHARACTERS: 'SEARCHCHARACTERS',
  FILTERCHARACTERS: 'FILTERCHARACTERS',
};
